DROP TABLE IF EXISTS rules;

CREATE TABLE rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    persistent BOOLEAN NOT NULL DEFAULT 0,
);